<?php

/**
 * @file
 * This module holds functions for entity events.
 */
use Drupal\Core\Entity\EntityInterface;
use Drupal\event_dispatcher\EntityEventDispatcherType;
use Drupal\event_dispatcher\Event\EntityEvent;
use Symfony\Component\EventDispatcher\Event;

/**
 * Implements hook_entity_insert().
 *
 * {@inheritdoc}
 */
function event_dispatcher_entity_insert(EntityInterface $entity) {
  $event_type = EntityEventDispatcherType::INSERT;
  $event = new EntityEvent($event_type, $entity);
  _event_dispatcher_dispatch($event_type, $event);
}

/**
 * Implements hook_entity_update().
 *
 * { @inheritdoc }
 */
function event_dispatcher_entity_update(EntityInterface $entity) {
  $event_type = EntityEventDispatcherType::UPDATE;
  $event = new EntityEvent($event_type, $entity);
  _event_dispatcher_dispatch($event_type, $event);
}

/**
 * Implements hook_entity_delete().
 *
 * {@inheritdoc}
 */
function event_dispatcher_entity_delete(EntityInterface $entity) {
  $event_type = EntityEventDispatcherType::DELETE;
  $event = new EntityEvent($event_type, $entity);
  _event_dispatcher_dispatch($event_type, $event);
}

/**
 * Helper method to dispatch an event.
 *
 * @param string $event_type
 *   The event type.
 * @param \Symfony\Component\EventDispatcher\Event $event
 *   The event to dispatch.
 */

function _event_dispatcher_dispatch($event_type, Event $event) {
  /** @var \Symfony\Component\EventDispatcher\EventDispatcher $dispatcher */
  $dispatcher = \Drupal::service('event_dispatcher');
  $dispatcher->dispatch($event_type, $event);
}
